POST http://localhost:8080/create
Content-Type: application/json

{
  "taskName": "Watch Series"
}

###
GET http://localhost:8080/getAllTodos

###
DELETE http://localhost:8080/delete/54E3083AC5EB49AFB27DABCBF0CC0731

###
