POST http://localhost:8080/create/todolist
Content-Type: application/json

{
  "todoListName": "Stationary"
}

###
POST http://localhost:8080/055074D2D6B04C68ABA7C747C75590C7/create
Content-Type: application/json

{
"taskName": "Buy Pencil",
"isPriority": false
}

###
GET http://localhost:8080/055074D2D6B04C68ABA7C747C75590C7/getAllTodos/

###
DELETE http://localhost:8080/delete/055074D2D6B04C68ABA7C747C75590C7

###
DELETE http://localhost:8080/087356EF1E9C495EA63D58A6EC24AA5C/delete/8072889A1EC04300B380D2BC6840F0E0

###
GET http://localhost:8080/viewAllTodoList

###